version: '3'
services:
  db:
    image: "postgres:11.4-alpine"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bundle exec rails server --port 3000 --binding 0.0.0.0
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
